name:                baastad
version:             0.1.0.0
github:              "atopuzov/baastad"
license:             BSD3
author:              "Aleksandar Topuzovic"
maintainer:          "aleksandar.topuzovic@gmail.com"
copyright:           "2019 Aleksandar Topuzovic"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/atopuzov/baastad#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- quickcheck-classes

library:
  source-dirs: src

executables:
  baastad-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - baastad
    - mtl
    - transformers

tests:
  baastad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - baastad
    - QuickCheck
    - quickcheck-classes
