name:                stack-ghc822
version:             0.1.0.0
github:              "atopuzov/stack-ghc822"
license:             BSD3
author:              "Aleksandar Topuzovic"
maintainer:          "aleksandar.topuzovic@gmail.com"
copyright:           "2020 Aleksandar Topuzovic"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/atopuzov/stack-ghc822#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  stack-ghc822-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stack-ghc822

tests:
  stack-ghc822-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stack-ghc822
