name:                par-con-hask
version:             0.1.0.0
github:              "atopuzov/par-con-hask"
license:             BSD3
author:              "Aleksandar Topuzovic"
maintainer:          "aleksandar.topuzovic@gmail.com"
copyright:           "2020 Aleksandar Topuzovic"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/atopuzov/par-con-hask#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- filepath
- stm
- network
- async
- distributed-process
- distributed-process-simplelocalnet

library:
  source-dirs: src

executables:
  par-con-hask-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - par-con-hask

tests:
  par-con-hask-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - par-con-hask
